### ISSUE TITLE
Triggers won't work when pressed together. 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [GivePass/x360ce#180]
```
What steps will reproduce the problem?
1.Using both triggers at the same time
2.Aim with left trigger and shoot with another (GTA IV)

What is the expected output? What do you see instead?
I expect to that I can hold aiming down the sight and fire weapon with the 
another but when I hold left trigger, I can't press the right one. Same thing 
happens vise versa. I can press both fine separately. 

What version of x360ce and Windows are you using?
v2.0.2.102, windows 7 ultimate

What gamepad are you using? On what version of drivers?
Saitek PS 2700 Rumble Pad

Please attach a log file created with Log=1 setting in x360ce.ini file,
and screenshot of x360ce app tab with you gamepad capabilities.

Issue report without Log will be DELETED as Invalid !

PS: It would be great if someone helps me with the force feedback of this 
device. It doesn't seem to work anywhere. In control panel, it doesn't show any 
option to test the force feedback.
```

Original issue reported on code.google.com by `Shams.i...@gmail.com` on 2 Aug 2011 at 3:56

Attachments:
- [x360ce_20110802-195205.log](https://storage.googleapis.com/google-code-attachments/x360ce/issue-180/comment-0/x360ce_20110802-195205.log)
- [x360ce.ini](https://storage.googleapis.com/google-code-attachments/x360ce/issue-180/comment-0/x360ce.ini)
- [Capture.PNG](https://storage.googleapis.com/google-code-attachments/x360ce/issue-180/comment-0/Capture.PNG)

**Comment by piyush008gupta** [comment]
https://youtu.be/ykpj_wiaCYQ   watch this video i couldnt believe all it took was to update my drivers to make the triggers work

**Comment by Cristy94** [comment]
Any news on this? Why is it closed?

**Comment by piyush008gupta** [comment]
i dont understand what do u want regarding the fix?

**Comment by Cristy94** [comment]
"Triggers won't work when pressed together." Using x360ce for Shadow of Mordor, I have to press LT + RT to shoot my bow but it doesn't work as both are on the same axis.

**Comment by piyush008gupta** [comment]
ok did u watch my full video regarding this fix

**Comment by piyush008gupta** [comment]
if u dont have any problem with allowing me to remotely access ur pc to
help u u can share ur TeamViewer id and i will fix it for u

**Comment by Cristy94** [comment]
The video links to dodgy sites, I just want an official solution with clean drivers or open-source drivers, not remote customer support from strangers online.

**Comment by piyush008gupta** [comment]
bro at that time the sites i used use to have clean content sorry about
your experience heres a direct link to the drivers.
https://drive.google.com/file/d/0B7bMzcSq8aMAVUNwYWlSTzBCXzg/view

**Comment by piyush008gupta** [comment]
download these and follow the video further. please if possible and this
fix helps please subscribe to my channel for future assistance.

**Comment by Cristy94** [comment]
Yeah, cause "wdfcoinstaller01009" sounds very safe.

**Comment by piyush008gupta** [comment]
whats ur problem bro these are official drivers pulled from microsoft
itself if u have problem believing me just download latest xbox controller
drivers they will have the same file these are just a rollback to previous
version the one included in windows 7

**Comment by Cristy94** [comment]
My bad, I read it as WDFCoinInstaller, too much crypto-miners lately :)
